repos:
  - repo: local
    hooks:
      - id: conventional-pre-commit
        name: Conventional Commit (local)
        entry: ./conventional-pre-commit.sh 
        verbose: true
        language: script
