- id: conventional-pre-commit
  name: Conventional Commit
  entry: bash -c './conventional-pre-commit.sh "$@" || true' --
  language: system
  description: Checks commit message for Conventional Commits formatting
  always_run: true
  stages: [commit-msg]
  verbose: true
