name: Update GitHub stats

on:
  workflow_dispatch:
  schedule:
    - cron: "28 8 * * *"

jobs:
  github-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: .github/workflows/github-stats/package-lock.json

      - name: Install packages
        working-directory: .github/workflows/github-stats
        run: npm install

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/workflows/github-stats
        run: npm start

      - name: Commit and push changes
        run: |-
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "Compiler GitHub Actions"
          git diff --quiet || (git add README.md && git commit -m "chore(README): update stats")
          git push
